name: Build and run integration tests

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build_and_run_integration_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v4
      
    - name: Setup .NET v6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Restore the dependencies
      run: dotnet restore
      
    - name: Build the app
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test HouseRentingSystem.Tests --no-build --verbosity normal
